---
#     _____ _                 _      ______         _   _
#    / ____(_)               | |    |  ____|       | | (_)
#   | (___  _ _ __ ___  _ __ | | ___| |__ __ _  ___| |_ _  ___  _ __
#    \___ \| | '_ ` _ \| '_ \| |/ _ \  __/ _` |/ __| __| |/ _ \| '_ \
#    ____) | | | | | | | |_) | |  __/ | | (_| | (__| |_| | (_) | | | |
#   |_____/|_|_| |_| |_| .__/|_|\___|_|  \__,_|\___|\__|_|\___/|_| |_|
#                      | |
#                      |_|
#

# SQLITE | MYSQL
PROVIDER: "SQLITE"

# Edit this only if 'PROVIDER' is on MYSQL
mysql_address: "SERVER ADDRESS"
mysql_user: "USER"
mysql_password: "YOUR PASSWORD"
mysql_db: "YOUR DB"

# Broadcast created system.
broadcast_message_created: true
broadcast_message_disband: true

# Activate or desactivate the entering and leaving messages.
entering_leaving: true

# Activate or deactivate the bank system (/f bank)
economy_system: false

# Activate or deactivate the war system (/f war)
war_system: true
# War duration in seconds
war_timer: 300

# Faction name limit.
min_faction_name_lenght: 3
max_faction_name_lenght: 16

# Power gained per kill and lost per death.
power_gain_per_kill: 1
power_lost_per_death: 1

# Worlds where the players can claim.
faction_worlds: ["world"]

# TRUE = ENABLE | FALSE = DISABLE
faction_pvp: false
alliance_pvp: false

# Time in seconds before invitations expire
invitation_expire_time: 30
allies_invitation_expire_time: 60

# Max members in a faction.
faction_max_members: 20

# Max allies in a faction.
faction_max_allies: 2

# Default power in a faction
default_power: 0

# Powers required for each claim.
# One - = 1 claim. If you setup 2 -, the max claim number would be 2.
# Usage: - POWERS NEEDED
claims:
  - 100
  - 500
  - 800
  - 1000
  - 2500
  - 5000

# Prefix usable in languages. {prefix}
PREFIX: "§6[§fSimpleFaction§6]§f"
PLAYER_ONLY: "{prefix} §cThis command can't be used in the console !"
MAP_HEADER: "§6--------------------(§f{X}§6, §f{Z}§6)--------------------"

# Banned faction names
banned_names: ["op", "staff", "admin", "fuck", "shit"]

zones_colors:
  "Wilderness": "§2"
  "Own-Faction": "§a"
  "Allies": "§e"
  "Enemies": "§c"